// Full circuit data for all 2026 F1 circuits
export const CIRCUITS_2026 = {
  'Albert Park': {
    fullName: 'Albert Park Grand Prix Circuit',
    location: 'Melbourne, Australia', country: 'Australia', countryCode: 'AUS',
    length: 5.278, corners: 14, lapRecord: '1:20.235', lapRecordHolder: 'Charles Leclerc', lapRecordYear: 2024,
    firstGP: 1996, totalRaces: 29,
    characteristics: ['Street Circuit', 'High Speed', 'Difficult Overtaking'],
    drsZones: 2, elevation: 0,
    description: 'Set in the heart of Melbourne\'s Albert Park, this street circuit winds through a picturesque public park. The smooth, fast layout rewards clean driving and setup precision. The circuit saw significant changes in 2022, creating more overtaking opportunities.',
    grandPrix: 'Australian Grand Prix',
    meetingName: 'Australian Grand Prix',
  },
  'Shanghai': {
    fullName: 'Shanghai International Circuit',
    location: 'Shanghai, China', country: 'China', countryCode: 'CHN',
    length: 5.451, corners: 16, lapRecord: '1:32.238', lapRecordHolder: 'Michael Schumacher', lapRecordYear: 2004,
    firstGP: 2004, totalRaces: 17,
    characteristics: ['Permanent Circuit', 'High Speed', 'Good Overtaking'],
    drsZones: 2, elevation: 5,
    description: 'The Shanghai International Circuit is one of the most modern circuits on the calendar. The hairpin at Turn 6-7 is one of the longest in F1, providing a key overtaking opportunity. The back straight is one of the fastest sections, with DRS a huge factor.',
    grandPrix: 'Chinese Grand Prix',
    meetingName: 'Chinese Grand Prix',
  },
  'Suzuka': {
    fullName: 'Suzuka Circuit',
    location: 'Suzuka, Japan', country: 'Japan', countryCode: 'JPN',
    length: 5.807, corners: 18, lapRecord: '1:30.983', lapRecordHolder: 'Lewis Hamilton', lapRecordYear: 2019,
    firstGP: 1987, totalRaces: 35,
    characteristics: ['Permanent Circuit', 'Very High Speed', 'Technical'],
    drsZones: 1, elevation: 44,
    description: 'Widely regarded as the greatest circuit in F1, Suzuka\'s figure-of-eight layout is unique. The legendary S-Curves, Degner, 130R and the Casio chicane create a sequence that demands total commitment. Many world championships have been decided here.',
    grandPrix: 'Japanese Grand Prix',
    meetingName: 'Japanese Grand Prix',
  },
  'Sakhir': {
    fullName: 'Bahrain International Circuit',
    location: 'Sakhir, Bahrain', country: 'Bahrain', countryCode: 'BRN',
    length: 5.412, corners: 15, lapRecord: '1:31.447', lapRecordHolder: 'Pedro de la Rosa', lapRecordYear: 2005,
    firstGP: 2004, totalRaces: 20,
    characteristics: ['Permanent Circuit', 'Medium Speed', 'Good Overtaking'],
    drsZones: 3, elevation: 3,
    description: 'The Bahrain International Circuit is a modern, purpose-built track in the desert. Night races here are a spectacle, with the floodlit track creating an incredible atmosphere. Three DRS zones and multiple hairpins make for excellent racing.',
    grandPrix: 'Bahrain Grand Prix',
    meetingName: 'Bahrain Grand Prix',
  },
  'Jeddah': {
    fullName: 'Jeddah Corniche Circuit',
    location: 'Jeddah, Saudi Arabia', country: 'Saudi Arabia', countryCode: 'SAU',
    length: 6.174, corners: 27, lapRecord: '1:29.708', lapRecordHolder: 'Lewis Hamilton', lapRecordYear: 2021,
    firstGP: 2021, totalRaces: 4,
    characteristics: ['Street Circuit', 'Very High Speed', 'Difficult Overtaking'],
    drsZones: 3, elevation: 0,
    description: 'The second-fastest circuit on the calendar, the Jeddah Corniche Circuit is a flowing street track along the Red Sea corniche. High-speed corners with little margin for error make this one of the most demanding tracks for drivers.',
    grandPrix: 'Saudi Arabian Grand Prix',
    meetingName: 'Saudi Arabian Grand Prix',
  },
  'Miami Gardens': {
    fullName: 'Miami International Autodrome',
    location: 'Miami, USA', country: 'USA', countryCode: 'USA',
    length: 5.412, corners: 19, lapRecord: '1:29.708', lapRecordHolder: 'Max Verstappen', lapRecordYear: 2023,
    firstGP: 2022, totalRaces: 4,
    characteristics: ['Street Circuit', 'High Speed', 'Good Overtaking'],
    drsZones: 3, elevation: 0,
    description: 'Built around the Hard Rock Stadium, the Miami International Autodrome brings F1 to the heart of one of America\'s most vibrant cities. The circuit features a mix of high-speed straights and technical sections.',
    grandPrix: 'Miami Grand Prix',
    meetingName: 'Miami Grand Prix',
  },
  'Monaco': {
    fullName: 'Circuit de Monaco',
    location: 'Monte Carlo, Monaco', country: 'Monaco', countryCode: 'MCO',
    length: 3.337, corners: 19, lapRecord: '1:12.909', lapRecordHolder: 'Lewis Hamilton', lapRecordYear: 2021,
    firstGP: 1950, totalRaces: 67,
    characteristics: ['Street Circuit', 'Slow Speed', 'Impossible Overtaking'],
    drsZones: 1, elevation: 42,
    description: 'The jewel in Formula 1\'s crown. Monaco is the oldest, most prestigious race on the calendar. The narrow streets, the Casino, the tunnel and the harbour create an unparalleled atmosphere. Qualifying is everything here — overtaking is nearly impossible.',
    grandPrix: 'Monaco Grand Prix',
    meetingName: 'Monaco Grand Prix',
  },
  'Montreal': {
    fullName: 'Circuit Gilles Villeneuve',
    location: 'Montreal, Canada', country: 'Canada', countryCode: 'CAN',
    length: 4.361, corners: 14, lapRecord: '1:13.078', lapRecordHolder: 'Valtteri Bottas', lapRecordYear: 2019,
    firstGP: 1978, totalRaces: 44,
    characteristics: ['Street Circuit', 'Medium Speed', 'Good Overtaking'],
    drsZones: 2, elevation: 0,
    description: 'Named after the legendary Canadian driver, the Circuit Gilles Villeneuve on Île Notre-Dame is one of the most popular races. The Wall of Champions at the final chicane has claimed many victories. Hard braking and full throttle sections make it tough on brakes.',
    grandPrix: 'Canadian Grand Prix',
    meetingName: 'Canadian Grand Prix',
  },
  'Catalunya': {
    fullName: 'Circuit de Barcelona-Catalunya',
    location: 'Barcelona, Spain', country: 'Spain', countryCode: 'ESP',
    length: 4.675, corners: 16, lapRecord: '1:16.330', lapRecordHolder: 'Max Verstappen', lapRecordYear: 2023,
    firstGP: 1991, totalRaces: 33,
    characteristics: ['Permanent Circuit', 'High Speed', 'Limited Overtaking'],
    drsZones: 2, elevation: 87,
    description: 'The Circuit de Barcelona-Catalunya is the spiritual home of Spanish motorsport. Extensively used for pre-season testing, every team knows this circuit intimately. The long Turn 3 complex and the final chicane are key reference points for setup.',
    grandPrix: 'Spanish Grand Prix',
    meetingName: 'Spanish Grand Prix',
  },
  'Spielberg': {
    fullName: 'Red Bull Ring',
    location: 'Spielberg, Austria', country: 'Austria', countryCode: 'AUT',
    length: 4.318, corners: 10, lapRecord: '1:05.619', lapRecordHolder: 'Carlos Sainz', lapRecordYear: 2020,
    firstGP: 1970, totalRaces: 36,
    characteristics: ['Permanent Circuit', 'High Speed', 'Very Good Overtaking'],
    drsZones: 3, elevation: 65,
    description: 'Nestled in the Styrian mountains, the Red Bull Ring is one of the shortest tracks on the calendar but produces some of the most exciting racing. Three strong DRS zones and multiple overtaking opportunities into Turn 3 and Turn 4 reward brave driving.',
    grandPrix: 'Austrian Grand Prix',
    meetingName: 'Austrian Grand Prix',
  },
  'Silverstone': {
    fullName: 'Silverstone Circuit',
    location: 'Silverstone, UK', country: 'United Kingdom', countryCode: 'GBR',
    length: 5.891, corners: 18, lapRecord: '1:27.097', lapRecordHolder: 'Max Verstappen', lapRecordYear: 2020,
    firstGP: 1950, totalRaces: 55,
    characteristics: ['Permanent Circuit', 'Very High Speed', 'Good Overtaking'],
    drsZones: 2, elevation: 16,
    description: 'The home of British motorsport and the venue for the very first F1 World Championship race in 1950. Silverstone\'s high-speed corners — Copse, Maggotts, Becketts and Chapel — are among the fastest in the world. The Wing straight provides DRS overtaking.',
    grandPrix: 'British Grand Prix',
    meetingName: 'British Grand Prix',
  },
  'Spa-Francorchamps': {
    fullName: 'Circuit de Spa-Francorchamps',
    location: 'Spa, Belgium', country: 'Belgium', countryCode: 'BEL',
    length: 7.004, corners: 19, lapRecord: '1:41.252', lapRecordHolder: 'Valtteri Bottas', lapRecordYear: 2018,
    firstGP: 1950, totalRaces: 52,
    characteristics: ['Permanent Circuit', 'Very High Speed', 'Good Overtaking'],
    drsZones: 2, elevation: 103,
    description: 'Many consider Spa-Francorchamps the greatest racing circuit in the world. The legendary Eau Rouge/Raidillon complex, Pouhon, and the 7km lap through the Ardennes forest create a truly epic challenge. The unpredictable weather adds another layer of complexity.',
    grandPrix: 'Belgian Grand Prix',
    meetingName: 'Belgian Grand Prix',
  },
  'Hungaroring': {
    fullName: 'Hungaroring',
    location: 'Budapest, Hungary', country: 'Hungary', countryCode: 'HUN',
    length: 4.381, corners: 14, lapRecord: '1:16.627', lapRecordHolder: 'Lewis Hamilton', lapRecordYear: 2020,
    firstGP: 1986, totalRaces: 39,
    characteristics: ['Permanent Circuit', 'Low Speed', 'Difficult Overtaking'],
    drsZones: 2, elevation: 35,
    description: 'The Hungaroring is one of the tightest circuits on the calendar, often called "Monaco without the barriers". The grippy surface and technical layout rewards qualifying pace. Turn 1 and Turn 2 offer the main overtaking opportunity, while the rest demands precision.',
    grandPrix: 'Hungarian Grand Prix',
    meetingName: 'Hungarian Grand Prix',
  },
  'Zandvoort': {
    fullName: 'Circuit Zandvoort',
    location: 'Zandvoort, Netherlands', country: 'Netherlands', countryCode: 'NED',
    length: 4.259, corners: 14, lapRecord: '1:11.097', lapRecordHolder: 'Max Verstappen', lapRecordYear: 2021,
    firstGP: 1952, totalRaces: 31,
    characteristics: ['Permanent Circuit', 'High Speed', 'Banked Turns'],
    drsZones: 2, elevation: 9,
    description: 'Restored to the calendar in 2021, the Circuit Zandvoort is a fan favourite nestled among the sand dunes. The steeply banked Hugenholtzbocht and the Arie Luyendyk turn make it unique. The narrow track makes overtaking challenging but battles are intense.',
    grandPrix: 'Dutch Grand Prix',
    meetingName: 'Dutch Grand Prix',
  },
  'Monza': {
    fullName: 'Autodromo Nazionale Monza',
    location: 'Monza, Italy', country: 'Italy', countryCode: 'ITA',
    length: 5.793, corners: 11, lapRecord: '1:21.046', lapRecordHolder: 'Rubens Barrichello', lapRecordYear: 2004,
    firstGP: 1950, totalRaces: 73,
    characteristics: ['Permanent Circuit', 'Extremely High Speed', 'Excellent Overtaking'],
    drsZones: 2, elevation: 0,
    description: 'The Temple of Speed. Monza is the fastest circuit on the F1 calendar and one of the oldest. The long straights into the Variante del Rettifilo and Variante Ascari create massive slipstreaming and DRS battles. The historic home of Ferrari and the Tifosi.',
    grandPrix: 'Italian Grand Prix',
    meetingName: 'Italian Grand Prix',
  },
  'Madrid': {
    fullName: 'IFEMA Madrid Circuit',
    location: 'Madrid, Spain', country: 'Spain', countryCode: 'ESP',
    length: 5.500, corners: 20, lapRecord: 'N/A', lapRecordHolder: 'TBA', lapRecordYear: 2026,
    firstGP: 2026, totalRaces: 1,
    characteristics: ['Street Circuit', 'High Speed', 'New Circuit'],
    drsZones: 3, elevation: 0,
    description: 'New for 2026, the Madrid street circuit runs through the IFEMA exhibition centre complex. The second Spanish race on the calendar, designed to bring F1 back to the Spanish capital after many years away.',
    grandPrix: 'Spanish Grand Prix',
    meetingName: 'Spanish Grand Prix',
  },
  'Baku': {
    fullName: 'Baku City Circuit',
    location: 'Baku, Azerbaijan', country: 'Azerbaijan', countryCode: 'AZE',
    length: 6.003, corners: 20, lapRecord: '1:43.009', lapRecordHolder: 'Charles Leclerc', lapRecordYear: 2019,
    firstGP: 2017, totalRaces: 8,
    characteristics: ['Street Circuit', 'High Speed', 'Good Overtaking'],
    drsZones: 2, elevation: 0,
    description: 'The Baku City Circuit runs through the historic streets of the Azerbaijani capital alongside the medieval Old City walls. The long 2.2km straight from Turn 16 to Turn 1 is one of the longest in F1, while the castle section is impossibly narrow.',
    grandPrix: 'Azerbaijan Grand Prix',
    meetingName: 'Azerbaijan Grand Prix',
  },
  'Marina Bay': {
    fullName: 'Marina Bay Street Circuit',
    location: 'Singapore', country: 'Singapore', countryCode: 'SGP',
    length: 4.940, corners: 19, lapRecord: '1:41.905', lapRecordHolder: 'Kevin Magnussen', lapRecordYear: 2018,
    firstGP: 2008, totalRaces: 16,
    characteristics: ['Street Circuit', 'Slow Speed', 'Night Race'],
    drsZones: 3, elevation: 0,
    description: 'Formula 1\'s original night race, Singapore is a unique spectacle under floodlights. The demanding street circuit passes iconic landmarks including the Raffles Hotel and the iconic Marina Bay Sands. The sweltering heat and humidity make it one of the most physically demanding.',
    grandPrix: 'Singapore Grand Prix',
    meetingName: 'Singapore Grand Prix',
  },
  'Austin': {
    fullName: 'Circuit of the Americas',
    location: 'Austin, USA', country: 'United States', countryCode: 'USA',
    length: 5.513, corners: 20, lapRecord: '1:36.169', lapRecordHolder: 'Charles Leclerc', lapRecordYear: 2019,
    firstGP: 2012, totalRaces: 12,
    characteristics: ['Permanent Circuit', 'High Speed', 'Excellent Overtaking'],
    drsZones: 2, elevation: 40,
    description: 'America\'s purpose-built F1 venue is a fan-favourite. The blind uphill Turn 1 is one of the most dramatic in the sport. The circuit borrows elements from iconic venues — Maggotts from Silverstone, the stadium section from Hockenheim.',
    grandPrix: 'United States Grand Prix',
    meetingName: 'United States Grand Prix',
  },
  'Mexico City': {
    fullName: 'Autodromo Hermanos Rodriguez',
    location: 'Mexico City, Mexico', country: 'Mexico', countryCode: 'MEX',
    length: 4.304, corners: 17, lapRecord: '1:17.774', lapRecordHolder: 'Valtteri Bottas', lapRecordYear: 2021,
    firstGP: 1963, totalRaces: 22,
    characteristics: ['Permanent Circuit', 'High Speed', 'Stadium Section'],
    drsZones: 3, elevation: 2285,
    description: 'At 2,285m above sea level, Mexico City is the highest circuit on the F1 calendar. The altitude reduces downforce and engine power significantly. The Foro Sol baseball stadium forms the iconic final sector, with passionate Mexican fans creating an incredible atmosphere.',
    grandPrix: 'Mexico City Grand Prix',
    meetingName: 'Mexico City Grand Prix',
  },
  'Interlagos': {
    fullName: 'Autodromo Jose Carlos Pace',
    location: 'São Paulo, Brazil', country: 'Brazil', countryCode: 'BRA',
    length: 4.309, corners: 15, lapRecord: '1:10.540', lapRecordHolder: 'Valtteri Bottas', lapRecordYear: 2018,
    firstGP: 1973, totalRaces: 38,
    characteristics: ['Permanent Circuit', 'High Speed', 'Good Overtaking'],
    drsZones: 2, elevation: 785,
    description: 'Interlagos is one of the most beloved circuits in F1. The anti-clockwise layout and changes in elevation create a challenging track that rewards raw talent. The volatile Brazilian weather often brings drama, and the passionate crowd is unforgettable.',
    grandPrix: 'São Paulo Grand Prix',
    meetingName: 'São Paulo Grand Prix',
  },
  'Las Vegas': {
    fullName: 'Las Vegas Strip Circuit',
    location: 'Las Vegas, USA', country: 'United States', countryCode: 'USA',
    length: 6.201, corners: 17, lapRecord: '1:35.490', lapRecordHolder: 'Oscar Piastri', lapRecordYear: 2024,
    firstGP: 2023, totalRaces: 2,
    characteristics: ['Street Circuit', 'High Speed', 'Night Race'],
    drsZones: 3, elevation: 0,
    description: 'Formula 1 on the famous Las Vegas Strip. The circuit runs past iconic hotels and casinos with three long straights producing incredible speeds. The night race under the neon lights of the Strip creates one of sport\'s most visually stunning spectacles.',
    grandPrix: 'Las Vegas Grand Prix',
    meetingName: 'Las Vegas Grand Prix',
  },
  'Lusail': {
    fullName: 'Lusail International Circuit',
    location: 'Lusail, Qatar', country: 'Qatar', countryCode: 'QAT',
    length: 5.380, corners: 16, lapRecord: '1:24.319', lapRecordHolder: 'Max Verstappen', lapRecordYear: 2023,
    firstGP: 2021, totalRaces: 3,
    characteristics: ['Permanent Circuit', 'High Speed', 'Night Race'],
    drsZones: 2, elevation: 0,
    description: 'Originally a motorcycle racing circuit, Lusail International Circuit is a flowing, modern track under floodlights. The sweeping high-speed corners demand confidence and commitment. The abrasive tarmac and heat create significant tyre management challenges.',
    grandPrix: 'Qatar Grand Prix',
    meetingName: 'Qatar Grand Prix',
  },
  'Yas Marina': {
    fullName: 'Yas Marina Circuit',
    location: 'Abu Dhabi, UAE', country: 'UAE', countryCode: 'UAE',
    length: 5.281, corners: 16, lapRecord: '1:26.103', lapRecordHolder: 'Max Verstappen', lapRecordYear: 2021,
    firstGP: 2009, totalRaces: 15,
    characteristics: ['Permanent Circuit', 'High Speed', 'Season Finale'],
    drsZones: 2, elevation: 0,
    description: 'The Yas Marina Circuit hosts the season finale every year. The 2021 Abu Dhabi Grand Prix was one of the most dramatic in the sport\'s history. The 2021 revised layout opened up more overtaking, and the circuit around the Yas Marina yacht basin is iconic.',
    grandPrix: 'Abu Dhabi Grand Prix',
    meetingName: 'Abu Dhabi Grand Prix',
  },
}

// Match OpenF1 circuit_short_name/location to our key
export function findCircuit(name) {
  if (!name) return null
  const n = name.toLowerCase()
  return Object.entries(CIRCUITS_2026).find(([k, v]) =>
    k.toLowerCase().includes(n) ||
    n.includes(k.toLowerCase()) ||
    v.location.toLowerCase().includes(n) ||
    v.meetingName.toLowerCase().includes(n) ||
    v.grandPrix.toLowerCase().includes(n)
  )?.[1] ?? null
}
